version: '3'

services:
  one-ws24:
    build: 
      context: '.'
      # args:
      #   ver: '8.3.12-1790'
    volumes:
      - ./descriptors:/descriptors        
  lb:
    image: dockercloud/haproxy
    links:
      - one-ws24
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 80:80
